[tool.poetry]
name = "easy-chat-document"
version = "0.1.0"
description = ""
authors = ["João Marcos <joaomarcosrs40@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
